channels:
- conda-forge
dependencies:
- python=3.8
- pip
- pip:
  - pytorch-lightning
  - torchmetrics
  - cloudpickle
  - torch
  - transformers
  - pandas
  - numpy
  - scipy
  - azureml-defaults
  - azureml-mlflow
  - ipadic
  - fugashi
name: pl-env-lang