channels:
- conda-forge
dependencies:
- python=3.8
- pip
- pip:
  - pytorch-lightning==1.2.4
  - cloudpickle==1.6.0
  - torch==1.8.0
  - torchvision==0.9.0
  - numpy
  - scipy
  - azureml-defaults
name: pl-env-image